version: '2.13.0'

services:
 database_booknable:
    image: postgres
    container_name: database_booknable
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=booknable
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local